final/finalproj/finalproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from users import views as user_views
from django.contrib.auth import views as authentication_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include('items.urls')),
    path('register/', user_views.register, name="register"),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final/finalproj/items/urls.py
from . import views
from django.urls import path

app_name = 'items'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('location', views.locations, name='locations'),
    path('room', views.rooms, name='rooms'),
    path('sort/<sort_by>', views.index_sorted, name='index_sorted'),
    path('location/sort/<sort_by>', views.locations_sorted, name='locations_sorted'),
    path('<int:item_id>', views.item_detail, name='item_detail'),
    path('location/<int:item_id>', views.location_detail, name='location_detail'),
    path('room/<int:item_id>', views.room_detail, name='room_detail'),
    path('add', views.create_item, name='create_item'),
    path('update/<int:id>', views.update_item, name='update_item'),
    path('delete/<int:id>', views.delete_item, name='delete_item'),
    path('location/add', views.create_location, name='create_location'),
    path('location/update/<int:id>', views.update_location, name='update_location'),
    path('location/delete/<int:id>', views.delete_location, name='delete_location'),
    path('room/add', views.create_room, name='create_room'),
    path('room/update/<int:id>', views.update_room, name='update_room'),
    path('room/delete/<int:id>', views.delete_room, name='delete_room'),
]

final/finalproj/items/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import MinValueValidator

# Create your models here.


class Room(models.Model):

    def __str__(self):
        return self.name

    name = models.CharField(max_length=200, unique=True)
    image = models.ImageField(upload_to='user_images/', default='rooms.jpg')
    description = models.CharField(max_length=1000, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)


class Location(models.Model):

    def __str__(self):
        return self.name

    name = models.CharField(max_length=200, unique=True)
    image = models.ImageField(upload_to='user_images/', default='closet.jpg')
    description = models.CharField(max_length=1000, blank=True)
    room_id = models.ForeignKey(Room, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)


class Item(models.Model):

    def __str__(self):
        return self.name

    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='user_images/', default='inventory.jpg')
    description = models.CharField(max_length=1000, blank=True)
    quantity = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    location_id = models.ForeignKey(Location, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("items:item-detail", kwargs={"pk": self.pk})

final/finalproj/items/forms.py
from django import forms
from .models import Item, Room, Location


class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ['name', 'image', 'description', 'quantity', 'location_id']
        labels = {
            'name': 'Item Name',
            'image': 'Item Image',
            'description': 'Item Description',
            'quantity': 'Item Quantity',
            'location_id': 'Location'
        }
        widgets = {
            'description': forms.Textarea(attrs={'cols': 80, 'rows': 10}),
        }


class LocationForm(forms.ModelForm):

    class Meta:
        model = Location
        fields = ['name', 'image', 'room_id', 'description']
        labels = {
            'name': 'Location Name',
            'image': 'Location Image',
            'description': 'Location Description',
            'room_id': 'Room'
        }
        widgets = {
            'description': forms.Textarea(attrs={'cols': 80, 'rows': 10}),
        }


class RoomForm(forms.ModelForm):

    class Meta:
        model = Room
        fields = ['name', 'image', 'description']
        labels = {
            'name': 'Room Name',
            'image': 'Room Image',
            'description': 'Room Description'
        }
        widgets = {
            'description': forms.Textarea(attrs={'cols': 80, 'rows': 10}),
        }

final/finalproj/items/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Item, Room, Location
from .forms import ItemForm, LocationForm, RoomForm

# Create your views here.


def index(request):
    item_list = Item.objects.all()
    context = {
        'item_list': item_list
    }
    return render(request, 'items/index.html', context)


def about(request):
    return render(request, 'items/about.html')


def locations(request):
    location_list = Location.objects.all()
    room_list = Room.objects.all()
    context = {
        'location_list': location_list,
        'room_list': room_list
    }
    return render(request, 'items/locations.html', context)


def rooms(request):
    room_list = Room.objects.all().order_by('name')
    context = {
        'room_list': room_list,
    }
    return render(request, 'items/rooms.html', context)


def index_sorted(request, sort_by):
    item_list = Item.objects.all().order_by(sort_by)
    context = {
        'item_list': item_list,
    }
    return render(request, 'items/index.html', context)


def locations_sorted(request, sort_by):
    location_list = Location.objects.all().order_by(sort_by)
    context = {
        'location_list': location_list,
    }
    return render(request, 'items/locations.html', context)


def item_detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item
    }
    return render(request, 'items/item-detail.html', context)


def location_detail(request, item_id):
    location = Location.objects.get(pk=item_id)
    context = {
        'location': location
    }
    return render(request, 'items/location-detail.html', context)


def room_detail(request, item_id):
    room = Room.objects.get(pk=item_id)
    context = {
        'room': room
    }
    return render(request, 'items/room-detail.html', context)


def create_item(request):
    item_form = ItemForm(request.POST or None, request.FILES or None)

    if item_form.is_valid():
        item_form.instance.created_by = request.user
        item_form.save()
        return redirect('items:index')

    return render(request, 'items/item-form.html', {'item_form': item_form})


def create_location(request):
    location_form = LocationForm(request.POST or None, request.FILES or None)

    if location_form.is_valid():
        location_form.instance.created_by = request.user
        location_form.save()
        return redirect('items:create_item')

    return render(request, 'items/location-form.html', {'location_form': location_form})


def create_room(request):
    room_form = RoomForm(request.POST or None, request.FILES or None)

    if room_form.is_valid():
        room_form.instance.created_by = request.user
        room_form.save()
        return redirect('items:create_location')

    return render(request, 'items/room-form.html', {'room_form': room_form})


def update_item(request, id):
    item = Item.objects.get(id=id)
    item_form = ItemForm(request.POST or None, request.FILES or None, instance=item)

    if item_form.is_valid():
        item_form.save()
        return redirect('items:index')

    return render(request, 'items/item-form.html', {'item_form': item_form, 'item': item})


def update_location(request, id):
    location = Location.objects.get(id=id)
    location_form = LocationForm(request.POST or None, request.FILES or None, instance=location)

    if location_form.is_valid():
        location_form.save()
        return redirect('items:locations')

    return render(request, 'items/location-form.html', {'location_form': location_form, 'location': location})


def update_room(request, id):
    room = Room.objects.get(id=id)
    room_form = RoomForm(request.POST or None, request.FILES or None, instance=room)

    if room_form.is_valid():
        room_form.save()
        return redirect('items:rooms')

    return render(request, 'items/room-form.html', {'room_form': room_form, 'room': room})


def delete_item(request, id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('items:index')

    return render(request, 'items/item-delete.html', {'item': item})


def delete_location(request, id):
    location = Location.objects.get(id=id)

    if request.method == 'POST':
        location.delete()
        return redirect('items:locations')

    return render(request, 'items/location-delete.html', {'location': location})


def delete_room(request, id):
    room = Room.objects.get(id=id)

    if request.method == 'POST':
        room.delete()
        return redirect('items:rooms')

    return render(request, 'items/room-delete.html', {'room': room})

final/finalproj/items/templates/items/about.html
{% extends 'items/base.html' %}

{% block body %}
    <h2 class="page-info">Hello! Welcome to your item inventory!</h2>
    <a href="{% url 'items:index' %}" class="btn btn-primary">See Your Inventory</a>
    <div class="row about">
        <h5>Most of us know where we keep things like our phones, keys, and wallets, but what about the things we don't use every day?</h5>
        <h5>That's where this app comes in. All you need to do is enter items into your inventory along with a location for that item.</h5>
        <h5>Add rooms such as the kitchen, your bedroom, etc. and locations such as a closet or the underside of your bed.</h5>
        <h5>The details are up to you!</h5>
        <h5>With this app, you will never have to search your whole house for that old photo album ever again!</h5>
    </div>
{% endblock %}

final/finalproj/items/templates/items/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'items/main.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Patua+One&family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/97b363f6ac.js" crossorigin="anonymous"></script>
    <title>Item Inventory{% if user.is_authenticated %} | {{ user.username }}{% endif %}</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="{% url 'items:index' %}" class="navbar-brand">{% if user.is_authenticated %}{{ user.username }}'s{% endif %} Item Inventory</a>
        <div class="navbar">
            <a href="{% url 'items:about' %}" class="nav-item nav-link">About</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="nav-item nav-link">Sign Out</a>
            {% else %}
                <a href="{% url 'login' %}" class="nav-item nav-link">Sign In</a>
                <a href="{% url 'register' %}" class="nav-item nav-link">Register</a>
            {% endif %}
        </div>
    </nav>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<div class="container">
    {% url 'login' as login %}
    {% url 'logout' as logout %}
    {% url 'register' as register %}
    {% if user.is_authenticated or request.path == login or request.path == logout or request.path == register %}
        {% block body %}
        {% endblock %}
    {% else %}
        <h2 class="page-info">Hello! Welcome to your item inventory!</h2>
        <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
        <div class="row about">
            <h5>Most of us know where we keep things like our phones, keys, and wallets, but what about the things we don't use every day?</h5>
            <h5>That's where this app comes in. All you need to do is enter items into your inventory along with a location for that item.</h5>
            <h5>Add rooms such as the kitchen, your bedroom, etc. and locations such as a closet or the underside of your bed.</h5>
            <h5>The details are up to you!</h5>
            <h5>With this app, you will never have to search your whole house for that old photo album ever again!</h5>
        </div>
    {% endif %}
</div>
</body>
</html>

final/finalproj/items/templates/items/index.html
{% extends 'items/base.html' %}

{% block body %}
    <h2 class="page-info">Your Items</h2>
    <h5 class="page-info">Here are the items in your inventory!</h5>

    <div class="row" id="button_row">
        <a href="{% url 'items:index' %}" class="btn btn-primary active">Items</a>
        <a href="{% url 'items:locations' %}" class="btn btn-primary">Locations</a>
        <a href="{% url 'items:rooms' %}" class="btn btn-primary">Rooms</a>
        <a href="{% url 'items:create_item' %}" class="btn btn-warning"><i class="fas fa-plus"></i> Add Item</a>

        <button class="btn btn-success dropdown-toggle" type="button" id="sortDropdownButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Sort
        </button>
        <div class="dropdown-menu" aria-labelledby="sortDropdownButton">
            <a class="dropdown-item" href="{% url 'items:index_sorted' sort_by='name' %}">By Name</a>
            <a class="dropdown-item" href="{% url 'items:index_sorted' sort_by='location_id' %}">By Location</a>
        </div>
    </div>

    {% for item in item_list %}
        {% if item.created_by == user %}
            <a href="{% url 'items:item_detail' item.id %}" class="item-link">
                <div class="row">
                    <div class="col-md-3">
                        <img src="{{ item.image.url }}" height="150px" alt="">
                    </div>
                    <div class="col-md-4">
                        <h3>{{ item.name }}</h3>
                        <p>Quantity: {{ item.quantity }}</p>
                        <p>Room: {{ item.location_id.room_id }}</p>
                        <p>Location: {{ item.location_id }}</p>
                    </div>
                </div>
            </a>
        {% endif %}
    {% endfor %}
{% endblock %}

final/finalproj/items/templates/items/item-delete.html
{% extends 'items/base.html' %}

{% block body %}
<form id="delete_form" method="POST">
    {% csrf_token %}
    <div class="row">
        <h2>Are you sure you want to delete {{ item.name }}?</h2>
        <button class="btn btn-danger" id="confirm_button" type="submit">Yes</button>
        <a class="btn btn-success" id="cancel_button" href="{% url 'items:index' %}">No</a>
    </div>
</form>
{% endblock %}

final/finalproj/items/templates/items/item-detail.html
{% extends 'items/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            {% if item.created_by == user %}
            <div class="col-md-6">
                <img src="{{ item.image.url }}" height="300px" alt="">
            </div>
            <div class="col-md-6">
                <h1>{{ item.name }}</h1>
                <h4>{{ item.description }}</h4>
                <p>Quantity: {{ item.quantity }}</p>
                <a href="{% url 'items:rooms' %}" class="item-link"><p>Room: {{ item.location_id.room_id }}</p></a>
                <a href="{% url 'items:locations' %}" class="item-link"><p>Location: {{ item.location_id }}</p></a>
                <a href="{% url 'items:update_item' item.id %}" class="btn btn-primary"><i class="fas fa-edit"></i> Edit</a>
                <a href="{% url 'items:delete_item' item.id %}" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Delete</a>
            </div>
            {% else %}
            <h3>You are not authorized to view this item!</h3>
            {% endif %}
        </div>
    </div>
{% endblock %}

final/finalproj/items/templates/items/item-form.html
{% extends 'items/base.html' %}

{% block body %}
    <div class="row">
        <form method="POST" enctype="multipart/form-data">
            <h2>Add/Edit Item</h2>
            {% csrf_token %}
            {{ item_form }}
            <a class="btn btn-warning" href="{% url 'items:create_location' %}"><i class="fas fa-plus"></i> Add Location</a>
            <button class="btn btn-primary" type="submit">Save</button>
            <button class="btn btn-success" onClick="history.back()">Cancel</button>
        </form>
    </div>
{% endblock %}

final/finalproj/items/templates/items/location-delete.html
{% extends 'items/base.html' %}

{% block body %}
<form id="delete_form" method="POST">
    {% csrf_token %}

    <div class="row">
        <h2>Are you sure you want to delete {{ location.name }}?</h2>
        <button class="btn btn-danger" id="confirm_button" type="submit">Yes</button>
        <a class="btn btn-success" id="cancel_button" href="{% url 'items:index' %}">No</a>
    </div>
</form>
{% endblock %}

final/finalproj/items/templates/items/location-detail.html
{% extends 'items/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            {% if location.created_by == user %}
            <div class="col-md-6">
                <img src="{{ location.image.url }}" height="300px" alt="">
            </div>
            <div class="col-md-6">
                <h1>{{ location.name }}</h1>
                <h4>{{ location.description }}</h4>
                <a href="{% url 'items:rooms' %}" class="item-link"><h4>{{ location.room_id }}</h4></a>
                <a href="{% url 'items:update_location' location.id %}" class="btn btn-primary"><i class="fas fa-edit"></i> Edit</a>
                <a href="{% url 'items:delete_location' location.id %}" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Delete</a>
            </div>
            {% else %}
            <h3>You are not authorized to view this location!</h3>
            {% endif %}
        </div>
    </div>
{% endblock %}

final/finalproj/items/templates/items/location-form.html
{% extends 'items/base.html' %}

{% block body %}
    <div class="row">
        <form method="POST" enctype="multipart/form-data">
            <h2>Add/Edit Location</h2>
            {% csrf_token %}
            {{ location_form }}
            <a class="btn btn-warning" href="{% url 'items:create_room' %}"><i class="fas fa-plus"></i> Add New Room</a>
            <button class="btn btn-primary" type="submit">Save</button>
            <button class="btn btn-success" onClick="history.back()">Back</button>
        </form>
    </div>
{% endblock %}

final/finalproj/items/templates/items/locations.html
{% extends 'items/base.html' %}

{% block body %}
    <h2 class="page-info">Your Locations</h2>
    <h5 class="page-info">Here are the different locations in each of your rooms!</h5>

    <div class="row" id="button_row">
        <a href="{% url 'items:index' %}" class="btn btn-primary">Items</a>
        <a href="{% url 'items:locations' %}" class="btn btn-primary active">Locations</a>
        <a href="{% url 'items:rooms' %}" class="btn btn-primary">Rooms</a>
        <a href="{% url 'items:create_item' %}" class="btn btn-warning"><i class="fas fa-plus"></i> Add Item</a>

        <button class="btn btn-success dropdown-toggle" type="button" id="sortDropdownButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Sort
        </button>
        <div class="dropdown-menu" aria-labelledby="sortDropdownButton">
            <a class="dropdown-item" href="{% url 'items:locations_sorted' sort_by='name' %}">By Name</a>
            <a class="dropdown-item" href="{% url 'items:locations_sorted' sort_by='room_id' %}">By Room</a>
        </div>
    </div>

    {% for location in location_list %}
        {% if location.created_by == user %}
            <a href="{% url 'items:location_detail' location.id %}" class="item-link">
                <div class="row">
                    <div class="col-md-3">
                        <img src="{{ location.image.url }}" height="150px" alt="">
                    </div>
                    <div class="col-md-4">
                        <h3>{{ location.name }}</h3>
                        <p>Room: {{ location.room_id }}</p>
                    </div>
                </div>
            </a>
        {% endif %}
    {% endfor %}
{% endblock %}

final/finalproj/items/templates/items/room-delete.html
{% extends 'items/base.html' %}

{% block body %}
<form id="delete_form" method="POST">
    {% csrf_token %}
    <div class="row">
        <h2>Are you sure you want to delete {{ room.name }}?</h2>
        <button class="btn btn-danger" id="confirm_button" type="submit">Yes</button>
        <a class="btn btn-success" id="cancel_button" href="{% url 'items:index' %}">No</a>
    </div>
</form>
{% endblock %}

final/finalproj/items/templates/items/room-detail.html
{% extends 'items/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            {% if room.created_by == user %}
            <div class="col-md-6">
                <img src="{{ room.image.url }}" height="300px" alt="">
            </div>
            <div class="col-md-6">
                <h1>{{ room.name }}</h1>
                <h4>{{ room.description }}</h4>
                <a href="{% url 'items:update_room' room.id %}" class="btn btn-primary"><i class="fas fa-edit"></i> Edit</a>
                <a href="{% url 'items:delete_room' room.id %}" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Delete</a>
            </div>
            {% else %}
            <h3>You are not authorized to view this room!</h3>
            {% endif %}
        </div>
    </div>
{% endblock %}

final/finalproj/items/templates/items/room-form.html
{% extends 'items/base.html' %}

{% block body %}
    <div class="row">
        <form method="POST" enctype="multipart/form-data">
            <h2>Add/Edit Room</h2>
            {% csrf_token %}
            {{ room_form }}
            <button class="btn btn-primary" type="submit">Save</button>
            <button class="btn btn-success" onClick="history.back()">Back</button>
        </form>
    </div>
{% endblock %}

final/finalproj/items/templates/items/rooms.html
{% extends 'items/base.html' %}

{% block body %}
    <h2 class="page-info">Your Rooms</h2>
    <h5 class="page-info">Here's are your rooms!</h5>

    <div class="row" id="button_row">
        <a href="{% url 'items:index' %}" class="btn btn-primary">Items</a>
        <a href="{% url 'items:locations' %}" class="btn btn-primary">Locations</a>
        <a href="{% url 'items:rooms' %}" class="btn btn-primary active">Rooms</a>
        <a href="{% url 'items:create_item' %}" class="btn btn-warning"><i class="fas fa-plus"></i> Add Item</a>
    </div>

    {% for room in room_list %}
        {% if room.created_by == user %}
            <a href="{% url 'items:room_detail' room.id %}" class="item-link">
                <div class="row">
                    <div class="col-md-3">
                        <img src="{{ room.image.url }}" height="150px" alt="">
                    </div>
                    <div class="col-md-4">
                        <h3>{{ room.name }}</h3>
                    </div>
                </div>
            </a>
        {% endif %}
    {% endfor %}
{% endblock %}